name: publish-blog

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '25'
    - uses: DeLaGuardo/setup-clojure@13.4
      with:
        lein: latest
    - name: Cache clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        # List all files containing dependencies:
        # key: cljdeps-${{ hashFiles('deps.edn') }}
        # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
        key: cljdeps-${{ hashFiles('project.clj') }}
        # key: cljdeps-${{ hashFiles('build.boot') }}
        restore-keys: cljdeps-

    - run: lein clean && lein run

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: rickerbh/rickerbh.github.io
        publish_branch: main
        publish_dir: ./public
