name: publish-blog

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DeLaGuardo/setup-graalvm@5.0
      with:
        graalvm: '21.0.0.2'
        java: 'java11'
    - uses: DeLaGuardo/setup-clojure@3.6
      with:
        lein: latest
    - run: lein clean && lein run

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: rickerbh/rickerbh.github.io
        publish_branch: master
        cname: hamishrickerby.com
