name: publish-blog

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
        version: '21.0.0.2'
        java-version: '11'
        components: 'native-image'
    - uses: DeLaGuardo/setup-clojure@10.0
      with:
        lein: latest
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        # List all files containing dependencies:
        # key: cljdeps-${{ hashFiles('deps.edn') }}
        # key: cljdeps-${{ hashFiles('deps.edn', 'bb.edn') }}
        key: cljdeps-${{ hashFiles('project.clj') }}
        # key: cljdeps-${{ hashFiles('build.boot') }}
        restore-keys: cljdeps-

    - run: lein clean && lein run

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: rickerbh/rickerbh.github.io
        publish_branch: master
        cname: hamishrickerby.com
